### ISSUE TITLE
Preferences file location is not correct

### ISSUE THREAD

**Issue by bmorgenthaler** [yaoxinghuo/alfred-jumpdesktop-workflow#2]
My preference file (named differently too) is at another location then what is currently hard coded.

Here is the path for my system:
`preferencesPath = os.path.join(os.environ["HOME"], "Library", "Preferences", "com.p5sys.jump.mac.viewer.web.plist")`

**macOS**: 11.6.1
**JumpDesktop**: 8.8.16

**Comment by yaoxinghuo** [comment]
Can you show your preference file's content: `com.p5sys.jump.mac.viewer.web.plist`
Does the preference file contains key: "path where JSON .jump files are stored" ?

**Comment by bmorgenthaler** [comment]
Sorry for the delayed reply, yes the preference file contains the path where the json .jump files are stored.  I think mine is in a different location because my version of JumpDesktop is not from the App Store but the developer directly.

**Comment by yaoxinghuo** [comment]
Thanks for your reply, I have changed the python script which checks both of the two preference files in commit https://github.com/yaoxinghuo/alfred-jumpdesktop-workflow/commit/c74ab5722c3c7b23dad4a8f606444c2a2c9afc25
